### ISSUE TITLE
separating `rewriteNode` to be done at rendering time

### ISSUE THREAD

**Issue by pkra** [krautzource/mathjax-sre-walker#13]
`rewriteNode` can be done server-side. 

This would reduce `chromify.js` by almost 50% and improve client-side performance.

**Comment by pkra** [comment]
As per F2F with @zorkow , this would not fit into SRE well. 

So something `sre-enrich.js` in this repo (or mathjax-node-sre) could to this as a post-processing step.

**Comment by pkra** [comment]
The hard part was done as part of #19.

**Comment by pkra** [comment]
Initial tests indicate that extracting the abstract tree from the DOM by recursing through the aria-owns structure instead of going data-attribute-skeleton=>rewrite to json=>parse as json => makeTree is an order of magnitude faster -- albeit on a laptop we're talking about 0.01ms vs 0.1ms.

Still, it's probably best to have an agnostic tree walker that picks up on aria-owns structure on the client while server-side provides ready-to-go aria-owns and -label structure.

**Comment by pkra** [comment]
cf. also https://github.com/krautzource/mathjax-sre-walker/issues/20#issuecomment-425740192

**Comment by pkra** [comment]
After playing around a whole lot more, it looks like we're headed for a split: 

* a role-tree-with-aria-owns walker module for the client (<1kb gzip'd) (which basically has nothing to do with mathjax/sre),
* an example of using sre to add such structure to mathjax output.

Not sure how to organize this here.

**Comment by zorkow** [comment]
Where does the info for the `role-tree-with-aria-owns` walker come from? So far we used the skeleton computed by SRE. So is that still necessary?

**Comment by pkra** [comment]
> Where does the info for the role-tree-with-aria-owns walker come from? So far we used the skeleton computed by SRE. So is that still necessary?

In my current "draft", the skeleton is still used in the server-side generation; but I suppose the information could be gathered directly from the output's data-semantic attributes.

**Comment by pkra** [comment]
This is basically addressed by #41, #42.

**Comment by pkra** [comment]
> In my current "draft", the skeleton is still used in the server-side generation; but I suppose the information could be gathered directly from the output's data-semantic attributes.

I was incorrect about this. The problem is that SRE output has no information on how to combine data-semantic-children and data-semantic-content. In the default example (quadratic equation), the top node has children 0, 23 and content 1 but the 1 actually goes in between 0 and 23 -  the skeleton reflects that. Later on, data-semantic-children="9,10,11" data-semantic-content="12,13" and the skeleton gives 9 12 10 13 11.

@zorkow is there a way to find out how to join "children" and "content"? E.g., infixop seems a possible piece of information but that seems like a path towards replicating large parts of SRE. 

Overall, it seems simpler (half the code) to not use the skeleton, i.e., if SRE could provide data-semantic-owns that gives the combined information.
