### ISSUE TITLE
rename or fork

### ISSUE THREAD

**Issue by pkra** [krautzource/mathjax-sre-walker#46]
The walker is now a generic "aria-owns / aria-label tree walker", with mathjax + SRE being "merely" a great example for creating suitable markup content.

The name of the repo is therefore somewhat misleading. Renaming is an option since no package was ever released but it might be more appropriate to create a separate fork and archive this repository so as to document the history clearly.

**Comment by pkra** [comment]
ping @zorkow @dpvc.

**Comment by zorkow** [comment]
Sounds like a good idea. Maybe put the old files into an `attic` directory for now and we can sift through them what could be retained.

**Comment by pkra** [comment]
Thanks @zorkow, I've moved old stuff to the attic. 

I'm still leaning towards a clean fork but will think about it some more.
